apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: metadata-service-grpc
  description: "gRPC API for entity metadata"
spec:
  type: grpc
  lifecycle: production
  owner: "group:default/content"
  definition:
    $text: ./src/main/proto/metadata.proto
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: metadata-service
  description: "gRPC service for entity metadata"
  tags:
    - java
    - grpc
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: spotify-portal-public-demo/metadata-service
    sonarqube.org/project-key: spotify-portal-public-demo_metadata-service
    grafana/dashboard-selector: metadata-service
    grafana/alert-label-selector: service_name=metadata-service
    backstage.io/kubernetes-id: metadata-service
    backstage.io/kubernetes-namespace: metadata-service
    backstage.io/kubernetes-label-selector: app=metadata-service
spec:
  type: service
  lifecycle: production
  owner: "group:default/content"
  system: "system:default/metadata"
  providesApis:
    - metadata-service-grpc
  consumesApis:
    - track-service-grpc
    - album-service-grpc
    - artist-service-grpc
  dependsOn:
    - component:track-service
    - component:album-service
    - component:artist-service
